### ISSUE TITLE
Text alignment issue on GNOME Web (and potentially Safari)

### ISSUE THREAD

**Issue by CosmicRaichu** [EwanCroft/website#3]
**Describe the bug**
In the About Me page, the section listing hobbies is misaligned when viewing using GNOME Web

**To Reproduce**
Visit https://ewancroft.neocities.org/about_me on GNOME Web

**Expected behavior**
The text should be properly aligned as observed in Firefox and Chromium

**Screenshots**
![Screenshot from 2023-09-21 22-43-37](https://github.com/EwanCroft/website/assets/145057115/f3a50167-9480-4211-88e7-b8b9a17668a8)

**Desktop (please complete the following information):**
 - OS: Fedora Workstation 38
 - Browser: Gnome Web
 - Version: 44.6

**Additional context**
I'm not really filing this bug because I am particularly worried about GNOME Web compatibility. It is more that I am concerned that because it is WebKit based that this could be an issue that effects more popular browsers like Safari. I cannot test this on a modern version of Safari as I do not own a Mac. If you can test this and check that the issue doesn't effect Safari, then I don't mind the issue being closed. Wouldn't be the first weirdness I had with GNOME Web.

**Comment by EwanCroft** [comment]
fixed by d8368aeaab2e3e21fca026674e5a14453e81e761 and b3ccaa80f0b18046a0c6809eb33e1afcdf45b127
