### ISSUE TITLE
drm_warn.js is redundant

### ISSUE THREAD

**Issue by CosmicRaichu** [EwanCroft/website#6]
**Is your feature request related to a problem? Please describe.**
Web Environment Integrity is an abandoned proposal now. There is no point in checking browsers for it anymore, and keeping it would be a waste of bandwidth. [See here.](https://chromestatus.com/feature/5796524191121408)

**Describe the solution you'd like**
Remove drm_warn.js and all references to it. It is a redundant check that won't serve any purpose now.

**Comment by EwanCroft** [comment]
Done in bf7695a5b2135b76b39e2710fad79aff2253dd5c.
